=== labiium/pytestlab/pytestlab/profiles/oscilloscope_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "manufacturer": {
            "type": "string"
        },
        "model": {
            "type": "string"
        },
        "vendor_id": {
            "type": "string"
        },
        "product_id": {
            "type": "string"
        },
        "device_type": {
            "type": "string"
        },
        "trigger": {
            "type": "object",
            "properties": {
                "modes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "slopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "channels": {
            "type": "object",
            "patternProperties": {
                "^[0-9]+$": {
                    "type": "object",
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "channel_range": {
                            "type": "object",
                            "properties": {
                                "min_val": {
                                    "type": "number"
                                },
                                "max_val": {
                                    "type": "number"
                                }
                            }
                        },
                        "input_coupling": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "input_impedance": {
                            "type": "number"
                        },
                        "probe_attenuation": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        },
                        "timebase": {
                            "type": "object",
                            "properties": {
                                "range": {
                                    "type": "object",
                                    "properties": {
                                        "min_val": {
                                            "type": "number"
                                        },
                                        "max_val": {
                                            "type": "number"
                                        }
                                    }
                                },
                                "horizontal_resolution": {
                                    "type": "number"
                                }
                            }
                        }
                    }
                }
            }
        },
        "bandwidth": {
            "type": "number"
        },
        "sampling_rate": {
            "type": "number"
        },
        "memory": {
            "type": "number"
        },
        "waveform_update_rate": {
            "type": "number"
        },
        "fft": {
            "type": "object",
            "properties": {
                "window_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "units": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "function_generator": {
            "type": "object",
            "properties": {
                "waveform_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "supported_states": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "offset": {
                    "type": "object",
                    "properties": {
                        "min_val": {
                            "type": "number"
                        },
                        "max_val": {
                            "type": "number"
                        }
                    }
                },
                "frequency": {
                    "type": "object",
                    "properties": {
                        "min_val": {
                            "type": "number"
                        },
                        "max_val": {
                            "type": "number"
                        }
                    }
                },
                "amplitude": {
                    "type": "object",
                    "properties": {
                        "min_val": {
                            "type": "number"
                        },
                        "max_val": {
                            "type": "number"
                        }
                    }
                }
            }
        }
    },
    "additionalProperties": true
}

=== labiium/pytestlab/pytestlab/profiles/keysight/DSOX1202G.json
{
    "manufacturer": "Keysight",
    "model": "DSOX1202G",
    "vendor_id": "0x2A8D",
    "product_id": "0x0397",
    "device_type": "oscilloscope",
    "trigger": {
        "types": [
            "HIGH",
            "LOW"
        ],
        "modes": [
            "EDGE",
            "GLITch",
            "PATTern",
            "SHOLd",
            "TRANsition",
            "TV",
            "SBUS1"
        ],
        "slopes": [
            "POS",
            "NEG",
            "EITH",
            "ALT"
        ]
    },
    "channels": {
        "1": {
            "description": "Analog Channel 1",
            "channel_range": {
                "min_val": -5,
                "max_val": 5
            },
            "input_coupling": [
                "DC",
                "AC"
            ],
            "input_impedance": 1e6,
            "probe_attenuation": [
                1,
                10
            ],
            "timebase": {
                "range": {
                    "min_val": 5e-9,
                    "max_val": 50
                },
                "horizontal_resolution": 1e-12
            }
        },
        "2": {
            "description": "Analog Channel 2",
            "channel_range": {
                "min_val": -5,
                "max_val": 5
            },
            "input_coupling": [
                "DC",
                "AC"
            ],
            "input_impedance": 1e6,
            "probe_attenuation": [
                1,
                10
            ],
            "timebase": {
                "range": {
                    "min_val": 5e-9,
                    "max_val": 50
                },
                "horizontal_resolution": 1e-12
            }
        }
    },
    "bandwidth": 70e6,
    "sampling_rate": 2e9,
    "memory": 2e6,
    "waveform_update_rate": 2e5,
    "fft": {
        "window_types": [
            "RECTangular",
            "HANNing",
            "FLATtop",
            "BHARris"
        ],
        "units": [
            "DECibel",
            "VRMS"
        ]
    },
    "function_generator": {
        "waveform_types": [
            "SINE",
            "SQUare",
            "RAMp",
            "PULse",
            "NOISe",
            "DC"
        ],
        "supported_states": [
            "ON",
            "OFF"
        ],
        "offset": {
            "min_val": -5,
            "max_val": 5
        },
        "frequency": {
            "min_val": 0.1,
            "max_val": 20e6
        },
        "amplitude": {
            "min_val": 2e-3,
            "max_val": 20
        }
    }
}
